### ISSUE TITLE
Running node with wallet

### ISSUE THREAD

**Issue by VascoVisser** [input-output-hk/cardano-sl#1993]
I am attempting to run the daedalus wallet on my linux box.

I can build the frontend and see it attempts to connect to the backend:
```
 [01:41:57:0943] [error] CardanoClientApi::syncProgress error: {
   "stack": "Error: connect ECONNREFUSED 127.0.0.1:8090\n    at Object.exports._errnoException (util.js:1050:11)\n    at exports._exceptionWithHostPort (util.js:1073:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)",
   "message": "connect ECONNREFUSED 127.0.0.1:8090",
   "code": "ECONNREFUSED",
   "errno": "ECONNREFUSED",
   "syscall": "connect",
   "address": "127.0.0.1",
   "port": 8090
 }
```

I have builde the backend as per instructions [1] and can launch the node, which reports the wallet part is build and enabled. 
```
$ stack exec -- cardano-node --system-start 1511917071
[Attention] We are in DEV mode
Asserts are ON
[Attention] Software is built with wallet part
System start time is 1511917071000000
Current time is 1511917078029341
Wallet is enabled!
...
```
However, it doesn't open the wallet socket. The node output shows repeatedly:
```
[node.worker.security:WARNING:ThreadId 24] [2017-11-29 01:59:13 CET] self: could not choose suitable alternative from []
[node.worker.security:ERROR:ThreadId 24] [2017-11-29 01:59:13 CET] self: enqueue instruction EnqueueAll {enqNodeType = NodeRelay, enqMaxAhead = MaxAhead 1, enqPrecedence = PHigh} failed to enqueue message MsgRequestBlockHeaders Nothing to forwarding sets [[]]
[node.worker.security:ERROR:ThreadId 24] [2017-11-29 01:59:13 CET] self: enqueue instruction EnqueueAll {enqNodeType = NodeRelay, enqMaxAhead = MaxAhead 1, enqPrecedence = PHigh} failed to enqueue message MsgRequestBlockHeaders Nothing to forwarding sets [[]]
[node.worker.subscription:ERROR:ThreadId 40] [2017-11-29 01:59:13 CET] dnsSubscriptionWorker: no relays found for index 1
[node.worker.subscription:ERROR:ThreadId 40] [2017-11-29 01:59:13 CET] dnsSubscriptionWorker: no relays found for index 1
[node.worker.subscription:ERROR:ThreadId 40] [2017-11-29 01:59:13 CET] dnsSubscriptionWorker: DNS failure for index 1: [NameError]
[node.worker.subscription:ERROR:ThreadId 40] [2017-11-29 01:59:13 CET] dnsSubscriptionWorker: DNS failure for index 1: [NameError]
```
Any pointers are appreciated.

[1] - https://github.com/input-output-hk/cardano-sl/blob/master/docs/how-to/build-cardano-sl-and-daedalus-from-source-code.md

**Comment by akegalj** [comment]
Hm I think our docs doesn't specify correct branch/commit from daedalus repo to build https://github.com/input-output-hk/cardano-sl/blob/master/docs/how-to/build-cardano-sl-and-daedalus-from-source-code.md#building-daedalus 

@denisshevchenko could this be it?

**Comment by VascoVisser** [comment]
Could this be related to:
https://forum.cardanohub.org/t/connecting-to-network-issue/1545

Because a blue screen with "Connecting to the network" is what is shown when the frontend cannot connect to the backend.
