### ISSUE TITLE
Error building Daedalus Bridge in Ubuntu 17.10 

### ISSUE THREAD

**Issue by zmeel** [input-output-hk/cardano-sl#2084]
After [errors](https://github.com/input-output-hk/cardano-sl/issues/1784) building Daedalus Bridge in Ubuntu Server 16.04.3 I setup a Docker with Ubuntu 17.10 and installed all the necessary components and start building Daedalus Bridge as per [instructions](https://github.com/input-output-hk/cardano-sl/blob/master/docs/how-to/build-cardano-sl-and-daedalus-from-source-code.md) with: `[nix-shell:~/cardano-sl]$ ./scripts/build/daedalus-bridge.sh`

After several hours of building the process stopped with errors like this:
<pre>
Successfully created your PureScript modules!
3. Building Bridge...
/usr/bin/nodejs: /nix/store/cr49q6vvyhfs48dg15ys3mghfzgc80i7-openssl-1.0.2l/lib/libssl.so.1.0.0: no version information available (required by /usr/bin/nodejs)
/usr/bin/nodejs: /nix/store/cr49q6vvyhfs48dg15ys3mghfzgc80i7-openssl-1.0.2l/lib/libssl.so.1.0.0: no version information available (required by /usr/bin/nodejs)
/usr/bin/nodejs: /nix/store/cr49q6vvyhfs48dg15ys3mghfzgc80i7-openssl-1.0.2l/lib/libssl.so.1.0.0: no version information available (required by /usr/bin/nodejs)
/usr/bin/nodejs: /nix/store/cr49q6vvyhfs48dg15ys3mghfzgc80i7-openssl-1.0.2l/lib/libcrypto.so.1.0.0: no version information available (required by /usr/bin/nodejs)
/usr/bin/nodejs: /nix/store/cr49q6vvyhfs48dg15ys3mghfzgc80i7-openssl-1.0.2l/lib/libcrypto.so.1.0.0: no version information available (required by /usr/bin/nodejs)
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm WARN deprecated bower@1.8.2: ...psst! Your project can stop working at any moment because its dependencies can change. Prevent this by migrating to Yarn: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
npm WARN deprecated wrench@1.3.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.

> uglifyjs-webpack-plugin@0.4.6 postinstall /home/cardano-sl/daedalus/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

node: /nix/store/cr49q6vvyhfs48dg15ys3mghfzgc80i7-openssl-1.0.2l/lib/libssl.so.1.0.0: no version information available (required by node)
node: /nix/store/cr49q6vvyhfs48dg15ys3mghfzgc80i7-openssl-1.0.2l/lib/libssl.so.1.0.0: no version information available (required by node)
node: /nix/store/cr49q6vvyhfs48dg15ys3mghfzgc80i7-openssl-1.0.2l/lib/libssl.so.1.0.0: no version information available (required by node)
node: /nix/store/cr49q6vvyhfs48dg15ys3mghfzgc80i7-openssl-1.0.2l/lib/libcrypto.so.1.0.0: no version information available (required by node)
node: /nix/store/cr49q6vvyhfs48dg15ys3mghfzgc80i7-openssl-1.0.2l/lib/libcrypto.so.1.0.0: no version information available (required by node)
npm WARN lifecycle daedalus-client-api@0.0.1~preinstall: cannot run in wd %s %s (wd=%s) daedalus-client-api@0.0.1 which psc || which purs || npm install purescript@0.11.5 /home/cardano-sl/daedalus
npm WARN lifecycle daedalus-client-api@0.0.1~postinstall: cannot run in wd %s %s (wd=%s) daedalus-client-api@0.0.1 bower cache clean && bower install /home/cardano-sl/daedalus
</pre>

I already have cardano-sl  running fine and connected to the mainnet. I would really like to run the wallet connected to the full node and contribute to Cardano but after several days of building I'm lost and could use some help.

Thanks,
Erik

**Comment by zmeel** [comment]
Did the whole build again on a virtual machine (running on a Synology D415+, 8Gb RAM) with a fresh install of Ubuntu server 17.10. Unfortunately, after 2.5 hours the build failed. Very frustrating! 

Content of log /home/cardano-sl/daedalus/npm-debug.log:
<pre>
[nix-shell:/home/cardano-sl]$ cat /home/cardano-sl/daedalus/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/root/.nvm/versions/node/v6.12.2/bin/node',
1 verbose cli   '/root/.nvm/versions/node/v6.12.2/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build:prod' ]
2 info using npm@3.10.10
3 info using node@v6.12.2
4 verbose run-script [ 'prebuild:prod', 'build:prod', 'postbuild:prod' ]
5 info lifecycle daedalus-client-api@0.0.1~prebuild:prod: daedalus-client-api@0.0.1
6 silly lifecycle daedalus-client-api@0.0.1~prebuild:prod: no script for prebuild:prod, continuing
7 info lifecycle daedalus-client-api@0.0.1~build:prod: daedalus-client-api@0.0.1
8 verbose lifecycle daedalus-client-api@0.0.1~build:prod: unsafe-perm in lifecycle true
9 verbose lifecycle daedalus-client-api@0.0.1~build:prod: PATH: /root/.nvm/versions/node/v6.12.2/lib/node_modules/npm/bin/node-gyp-bin:/home/cardano-sl/daedalus/node_modules/.bin:/nix/store/2xqlcc9yw8nmgiglc9w9dmcigy2mif6l-openssh-7.5p1/bin:/nix/store/3hprjz6f0lq1xs9wixijmq5hdfl6xh2c-autoconf-2.69/bin:/nix/store/9hd7kcbcmjqp3q2xx04qzn5a61i862jz-automake-1.15.1/bin:/nix/store/wx061qkgvapwy001hhf3nznchkxr079c-gettext-0.19.8/bin:/nix/store/nyp7yphvzc1qzyj8lbw11gv8maj5cdlv-libtool-2.4.6/bin:/nix/store/fkkx3zv0yfsl46a24lz5g56ldbbxwkmd-gnum4-1.4.18/bin:/nix/store/jn350na5wcshwsixpq1wbskdp7r3x0r3-openssl-1.0.2l-bin/bin:/nix/store/vzqdp5c6ki9990lywbbxyc8bnic6mcw6-git-2.14.2/bin:/nix/store/gwzv8yf3kc751g27y602h4w9iy1anbps-bsdiff-4.3/bin:/nix/store/zy3pprbx3226xnw9c9p58pkphfjsr8wi-happy-1.19.7/bin:/nix/store/bj0qcghvlam4zrw9bi0h205zkvk2348m-cpphs-1.20.8/bin:/nix/store/x7gj63y7i2451bzg5h4pnqkir5wh9q6y-cabal-install-2.0.0.0/bin:/nix/store/3pb86cjaxmqsvar0ka3sx5qyfj2xjqxa-stack-1.5.1/bin:/nix/store/rzqyfil4xmja85w5sm13m107j1zm8d7s-ghc-8.0.2/bin:/nix/store/15axh70yqanvivgi69ns8sx7cjydqdx3-pkg-config-0.29.2/bin:/nix/store/bl1mv4i6ywns4hy0nvbdn93m9i12ryna-patchelf-0.9/bin:/nix/store/dy1fjqfnk1w0q2nix38b21cjqx218val-paxctl-0.9/bin:/nix/store/kd7vb1afwvm2k65n9qjdw767w6lnwsrd-gcc-wrapper-6.4.0/bin:/nix/store/g65l985579ri87i8m3906a2nmyrl24a2-gcc-6.4.0/bin:/nix/store/z470j6lybdsy4ql972k392490bprhd2g-binutils-2.28.1/bin:/nix/store/50h9s25lzbs3a8s3rvpd02vj6l28din8-glibc-2.25-49-bin/bin:/nix/store/d4yib20lqn7krrqmm0wwbwjxjfa78xqp-coreutils-8.28/bin:/nix/store/d4yib20lqn7krrqmm0wwbwjxjfa78xqp-coreutils-8.28/bin:/nix/store/871adhqrxl37bpi5w9g9g6y0i1n4f9cd-findutils-4.6.0/bin:/nix/store/kkrg56qh1l655bcdr6amyp7k59ndf81z-diffutils-3.6/bin:/nix/store/h5c2vfaxhpv7v0p1vlh3h7sdiphsi4rv-gnused-4.4/bin:/nix/store/s6wz7l5h0ya6qciy0xcxwv05l50snfy8-gnugrep-3.1/bin:/nix/store/pyqzyl3yvam1magahsm8xahx5hs1ngh9-gawk-4.1.4/bin:/nix/store/kpnj0h0340wd0i86q0523527ikbz62ll-gnutar-1.29/bin:/nix/store/abk6h8g0hj6dyk75h320mgls3ygshl0w-gzip-1.8/bin:/nix/store/by3lqpgph3c4maz6vb2xhd64vhagfc67-bzip2-1.0.6.0.1-bin/bin:/nix/store/8g2x5qjqyv9a7glmvpzv1wylnbf1cwvw-gnumake-4.2.1/bin:/nix/store/flb9ar1xdd13c606aa4my9miy3iv4vyk-bash-4.4-p12/bin:/nix/store/44dbwrwfy6lj45jy02d0rjbj9930nwf3-patch-2.7.5/bin:/nix/store/zv86mp9qr1kk2sxv174fxrmly82wakr0-xz-5.2.3-bin/bin:/root/.nix-profile/bin:/root/.nix-profile/sbin:/root/.nvm/versions/node/v6.12.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
10 verbose lifecycle daedalus-client-api@0.0.1~build:prod: CWD: /home/cardano-sl/daedalus
11 silly lifecycle daedalus-client-api@0.0.1~build:prod: Args: [ '-c',
11 silly lifecycle   'npm run clean && mkdir dist && cross-env NODE_ENV=prod ./node_modules/.bin/webpack --config webpack.config.babel.js --progress && cross-env NODE_ENV=prod ./node_modules/.bin/webpack --config webpack.config.babel.js --progress --bail' ]
12 silly lifecycle daedalus-client-api@0.0.1~build:prod: Returned: code: 2  signal: null
13 info lifecycle daedalus-client-api@0.0.1~build:prod: Failed to exec build:prod script
14 verbose stack Error: daedalus-client-api@0.0.1 build:prod: `npm run clean && mkdir dist && cross-env NODE_ENV=prod ./node_modules/.bin/webpack --config webpack.config.babel.js --progress && cross-env NODE_ENV=prod ./node_modules/.bin/webpack --config webpack.config.babel.js --progress --bail`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v6.12.2/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v6.12.2/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:920:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
15 verbose pkgid daedalus-client-api@0.0.1
16 verbose cwd /home/cardano-sl/daedalus
17 error Linux 4.13.0-16-generic
18 error argv "/root/.nvm/versions/node/v6.12.2/bin/node" "/root/.nvm/versions/node/v6.12.2/bin/npm" "run" "build:prod"
19 error node v6.12.2
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error daedalus-client-api@0.0.1 build:prod: `npm run clean && mkdir dist && cross-env NODE_ENV=prod ./node_modules/.bin/webpack --config webpack.config.babel.js --progress && cross-env NODE_ENV=prod ./node_modules/.bin/webpack --config webpack.config.babel.js --progress --bail`
22 error Exit status 2
23 error Failed at the daedalus-client-api@0.0.1 build:prod script 'npm run clean && mkdir dist && cross-env NODE_ENV=prod ./node_modules/.bin/webpack --config webpack.config.babel.js --progress && cross-env NODE_ENV=prod ./node_modules/.bin/webpack --config webpack.config.babel.js --progress --bail'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the daedalus-client-api package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run clean && mkdir dist && cross-env NODE_ENV=prod ./node_modules/.bin/webpack --config webpack.config.babel.js --progress && cross-env NODE_ENV=prod ./node_modules/.bin/webpack --config webpack.config.babel.js --progress --bail
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs daedalus-client-api
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls daedalus-client-api
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
</pre>

**Comment by zmeel** [comment]
This is probably all related to difference in versions of libraries, nodejs and npm.
