### ISSUE TITLE
Fail to build  daedalus wallet   on Ubuntu 16.04.3 LTS

### ISSUE THREAD

**Issue by cmatomic** [input-output-hk/cardano-sl#2208]
I'm trying to compile daedalus wallet on Ubuntu 16.04 
[npm-debug.log](https://github.com/input-output-hk/cardano-sl/files/1594502/npm-debug.log)

How do I resolve this error?

**Comment by zmeel** [comment]
<pre>
46205 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
46205 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
46205 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
46205 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
46206 verbose stack Error: v8-debug@0.7.7 install: `node-pre-gyp install --fallback-to-build`
46206 verbose stack Exit status 1
46206 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
46206 verbose stack     at emitTwo (events.js:126:13)
46206 verbose stack     at EventEmitter.emit (events.js:214:7)
46206 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
46206 verbose stack     at emitTwo (events.js:126:13)
46206 verbose stack     at ChildProcess.emit (events.js:214:7)
46206 verbose stack     at maybeClose (internal/child_process.js:925:16)
46206 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
46207 verbose pkgid v8-debug@0.7.7
46208 verbose cwd /home/cmatomic/daedalus
46209 verbose Linux 4.10.0-42-generic
46210 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "install"
46211 verbose node v8.9.3
46212 verbose npm  v5.6.0
46213 error code ELIFECYCLE
46214 error errno 1
46215 error v8-debug@0.7.7 install: `node-pre-gyp install --fallback-to-build`
46215 error Exit status 1
46216 error Failed at the v8-debug@0.7.7 install script.
46216 error This is probably not a problem with npm. There is likely additional logging output above.
46217 verbose exit [ 1, true ]
</pre>

Did you install `node-pre-gyp`?

**Comment by cmatomic** [comment]
I do not have that package "node-pre-gyp"  available for my system , I have a similar node-gyp
in the next file are all NODE packages installed on my system
[NodePackagesInstalled.txt](https://github.com/input-output-hk/cardano-sl/files/1594742/NodePackagesInstalled.txt)
in the next file are all the "node" packages available for my system
[allpackagesNODE.txt](https://github.com/input-output-hk/cardano-sl/files/1594743/allpackagesNODE.txt)

**Comment by cmatomic** [comment]
I installed the missing "node-pre-gyp" package through NPM, gave the same error .

**Comment by erikd** [comment]
I have started a cardano/daedelus build script for Linux at https://github.com/erikd/cardano-linux-pkg . Its not working yet, but I hope to get it working in the next day or two.

**Comment by cmatomic** [comment]
I installed the missing package "node-pre-gyp via npm " I got a similar error.
this is what shows my treminal
[TreminalOutPunt.txt](https://github.com/input-output-hk/cardano-sl/files/1594815/TreminalOutPunt.txt)

**Comment by p-alik** [comment]
actually it's an issue of [dadalus](https://github.com/input-output-hk/daedalus) repository.

Helpful [build instruction](https://github.com/h4ck3rm1k3/daedalus/blob/master/README.md).
