### ISSUE TITLE
issues using swagger-codegen on wallet swagger.json spec.

### ISSUE THREAD

**Issue by ljackson** [input-output-hk/cardano-sl#2268]
Wanting to do some client codegen for a test client project to the wallet but found that swagger codegen doesn't parse the swagger spec generated by the code on develop branch.

I used the SwaggerParser python lib  (pip install swagger-parser)

The results are wonder what the dev's think on this would like to be able to have valid swagger to auto-gen client code. Thx

python test-swgger.py 
Traceback (most recent call last):
  File "test-swgger.py", line 2, in <module>
    parser = SwaggerParser(swagger_path='./wallet-new/spec/swagger.json')
  File "/usr/local/lib/python2.7/dist-packages/swagger_parser/swagger_parser.py", line 72, in __init__
    raise ValueError('{0} is not a valid swagger2.0 file: {1}'.format(swagger_path,  e))
ValueError: ./wallet-new/spec/swagger.json is not a valid swagger2.0 file: {'description': '', 'schema': {'x-scope': [''], '$ref': '#/definitions/CTx'}} is not valid under any of the given schemas

Failed validating u'oneOf' in schema[u'properties'][u'paths'][u'patternProperties'][u'^/'][u'properties'][u'post'][u'properties'][u'responses'][u'patternProperties'][u'^([0-9]{3})$|^(default)$']:
    {u'oneOf': [{u'$ref': u'#/definitions/response'},
                {u'$ref': u'#/definitions/jsonReference'}]}

On instance[u'paths']['/api/v0/papervend/redemptions/ada'][u'post'][u'responses']['200']:
    {'description': '',
     'schema': {'$ref': '#/definitions/CTx', 'x-scope': ['']}}

**Comment by p-alik** [comment]
@ljackson, here is also a [comment](https://github.com/input-output-hk/daedalus/issues/611#issuecomment-355822634) with regard to `swagger.json`

**Comment by ljackson** [comment]
Agreed however that was on master If i read it correctly and the comment was to see develop. This parsing error is on develop branch thus why I wanted to know if the Cardano team was aware or if I should fix it and submit a pull request. :)
