### ISSUE TITLE
build of explorer web ui failed

### ISSUE THREAD

**Issue by p-alik** [input-output-hk/cardano-sl#2346]
I've been tried to follow [How to run Explorer Web UI](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/how-to/run-explorer-web-ui.md) description.

My environment:

- Ubuntu 16.04
- `nix-env` packages:
  - electron-1.7.9
  - nix-1.11.16
  - nodejs-6.11.5
  - yarn-1.3.2

Unfortunately the execution of  [build-explorer-frontend.sh](https://github.com/input-output-hk/cardano-sl/blob/develop/explorer/frontend/scripts/build-explorer-frontend.sh) ends in exception:

```
ERROR in ./src/index.css
Module build failed: 
 @ ./src/index.css
 @ ./src/index.js
 @ multi babel-polyfill ./node_modules/js-polyfills/polyfill.js ./node_modules/js-polyfills/keyboard.js ./src/index.js

ERROR in ./src/Main.purs
Module build failed: Error: compilation failed
    at ChildProcess.<anonymous> (/opt/devel/cardano/cardano-sl/explorer/frontend/node_modules/purs-loader/lib/compile.js:53:18)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Socket.<anonymous> (internal/child_process.js:351:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)
 @ ./src/index.js 5:12-34
 @ multi babel-polyfill ./node_modules/js-polyfills/polyfill.js ./node_modules/js-polyfills/keyboard.js ./src/index.js

ERROR in ./src/Explorer/State.purs
Module build failed: Error: purs-loader failed
    at /opt/devel/cardano/cardano-sl/explorer/frontend/node_modules/purs-loader/lib/index.js:303:27
    at Array.forEach (native)
    at /opt/devel/cardano/cardano-sl/explorer/frontend/node_modules/purs-loader/lib/index.js:302:33
    at tryCatcher (/opt/devel/cardano/cardano-sl/explorer/frontend/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/devel/cardano/cardano-sl/explorer/frontend/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/opt/devel/cardano/cardano-sl/explorer/frontend/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/opt/devel/cardano/cardano-sl/explorer/frontend/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/opt/devel/cardano/cardano-sl/explorer/frontend/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/opt/devel/cardano/cardano-sl/explorer/frontend/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/opt/devel/cardano/cardano-sl/explorer/frontend/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/opt/devel/cardano/cardano-sl/explorer/frontend/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
 @ ./src/index.js 9:13-45
 @ multi babel-polyfill ./node_modules/js-polyfills/polyfill.js ./node_modules/js-polyfills/keyboard.js ./src/index.js

ERROR in /opt/devel/cardano/cardano-sl/explorer/frontend/node_modules/purescript-psa/output/Control.Monad.Eff.Exception/foreign.js:25
    throw e;
    ^

Error: `purs` executable not found.
    at Object.exports.error (/opt/devel/cardano/cardano-sl/explorer/frontend/node_modules/purescript-psa/output/Control.Monad.Eff.Exception/foreign.js:8:10)
    at Object.$$throw [as throw] (/opt/devel/cardano/cardano-sl/explorer/frontend/node_modules/purescript-psa/output/Control.Monad.Eff.Exception/index.js:58:45)
    at /opt/devel/cardano/cardano-sl/explorer/frontend/node_modules/purescript-psa/output/Main/index.js:480:72
    at ChildProcess.<anonymous> (/opt/devel/cardano/cardano-sl/explorer/frontend/node_modules/purescript-psa/output/Node.ChildProcess/foreign.js:106:9)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:217:12)
    at onErrorNT (internal/child_process.js:376:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

Child html-webpack-plugin for "index.html":
     1 asset
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.tpl.html] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.tpl.html 919 bytes {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 488 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 495 bytes {0} [built]
        + 1 hidden module
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js?importLoaders=1!node_modules/postcss-loader/lib/index.js!src/index.css:
     7 assets
    [./node_modules/css-loader/index.js?importLoaders=1!./node_modules/postcss-loader/lib/index.js!./src/index.css] ./node_modules/css-loader?importLoaders=1!./node_modules/postcss-loader/lib!./src/index.css 198 kB {0} [built]
    [./static/fonts/Montserrat-Medium.otf] ./static/fonts/Montserrat-Medium.otf 58 bytes {0} [built]
    [./static/fonts/Montserrat-SemiBold.otf] ./static/fonts/Montserrat-SemiBold.otf 58 bytes {0} [built]
    [./static/fonts/Montserrat-Thin.otf] ./static/fonts/Montserrat-Thin.otf 58 bytes {0} [built]
    [./static/fonts/montserrat-bold_[allfont.ru].ttf] ./static/fonts/montserrat-bold_[allfont.ru].ttf 58 bytes {0} [built]
    [./static/fonts/montserrat-light_[allfont.ru].ttf] ./static/fonts/montserrat-light_[allfont.ru].ttf 58 bytes {0} [built]
    [./static/fonts/montserrat_[allfont.ru].ttf] ./static/fonts/montserrat_[allfont.ru].ttf 58 bytes {0} [built]
    [./static/images/header_300517.jpg] ./static/images/header_300517.jpg 58 bytes {0} [built]
        + 1 hidden module
    
    ERROR in /opt/devel/cardano/cardano-sl/explorer/frontend/node_modules/purescript-psa/output/Control.Monad.Eff.Exception/foreign.js:25
        throw e;
        ^
    
    Error: `purs` executable not found.
        at Object.exports.error (/opt/devel/cardano/cardano-sl/explorer/frontend/node_modules/purescript-psa/output/Control.Monad.Eff.Exception/foreign.js:8:10)
        at Object.$$throw [as throw] (/opt/devel/cardano/cardano-sl/explorer/frontend/node_modules/purescript-psa/output/Control.Monad.Eff.Exception/index.js:58:45)
        at /opt/devel/cardano/cardano-sl/explorer/frontend/node_modules/purescript-psa/output/Main/index.js:480:72
        at ChildProcess.<anonymous> (/opt/devel/cardano/cardano-sl/explorer/frontend/node_modules/purescript-psa/output/Node.ChildProcess/foreign.js:106:9)
        at emitOne (events.js:96:13)
        at ChildProcess.emit (events.js:188:7)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:217:12)
        at onErrorNT (internal/child_process.js:376:16)
        at _combinedTickCallback (internal/process/next_tick.js:80:11)
        at process._tickCallback (internal/process/next_tick.js:104:9)
    
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Done generating explorer purescript frontend.

```

**Comment by thinkocapo** [comment]
hmm try:
`npm install -g purescript`
and if still no luck, then add the purescript binary location to your PATH variable

I'm pretty sure this is what I did to get it to work.

They should maybe update the tutorial to remind people to npm install purescript.

**Comment by p-alik** [comment]
With regard to @thinkocapo 's advice 
`nix-env -i purescript` solved the `build-explorer-frontend.sh` issue for me.
