### ISSUE TITLE
Error in build-explorer-frontend installation

### ISSUE THREAD

**Issue by fl0dev** [input-output-hk/cardano-sl#2483]
hey there

i tried to install Dadealus on Manjaro (ArchLinux). 
The most steps are done, but running ./build-explorer-frontend.sh exited with 87 errors... 

It's starts with following lines, so it seems to be an error in the package

`ERROR in ./src/index.css
Module build failed: 

ERROR in ./src/Main.purs
Module build failed: Error: compilation failed
    at ChildProcess.<anonymous> (/home/flo/Programme/cardano-sl/explorer/frontend/node_modules/purs-loader/lib/compile.js:53:18)
    at ChildProcess.emit (events.js:160:13)
    at maybeClose (internal/child_process.js:943:16)
    at Socket.stream.socket.on (internal/child_process.js:363:11)
    at Socket.emit (events.js:160:13)
    at Pipe._handle.close [as _onclose] (net.js:562:12)
 @ ./src/index.js 5:12-34
 @ multi babel-polyfill ./node_modules/js-polyfills/polyfill.js ./node_modules/js-polyfills/keyboard.js ./src/index.js

...
`

Anyone any ideas to fix it?

**Comment by rvl** [comment]
Hi! Do you have the purescript compiler (`purs`) in your `PATH`?
